version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    volumes:
      - ../proto:/app/proto
    networks:
      - grpc-network

  envoy:
    build:
      context: ./envoy
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - grpc-network

networks:
  grpc-network:
    driver: bridge 